### ISSUE TITLE
NoneType Error

### ISSUE THREAD

**Issue by yasoob** [waartaa/ircb#40]
I got the following error when I tried to open 0.0.0.0:9000

```
[2015-12-26 02:07:40][   bouncer   ERROR] get_bot_handle error: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/yasoob/Desktop/ircb/ircb/bouncer.py", line 110, in get_bot_handle
    key = network.id
AttributeError: 'NoneType' object has no attribute 'id'
```

I followed the following steps:

```
$ python3 setup.py develop
$ ircb users create yasoob yasoob.khld@gmail.com <password>
$ ircb networks create yasoob Freenode irc.freenode.net 6665 yasoob
$ ircb runserver
```

**Comment by yasoob** [comment]
@sayanchowdhury did you get any chance to check this out?

**Comment by rtnpro** [comment]
Hey  @yasoob 

You are not supposed to open the endpoint over a browser, but using a IRC client, for example, Xchat, irssi, etc.

Readme says this:

```
You'll get an access token as an output of the above. Use this as server password when configuring your IRC client to connect to ircb
```

If it is not clear, from the README, feel free to suggest improvements :)

I hope that this solves your issue.

**Comment by yasoob** [comment]
AAhhh, I was pulling my hair out :-| Let me try this. Thanks! I will close
this issue once I verify the solution. I would be more than happy to
improve the docs. Thanks again!

Kind regards,
Muhammad Yasoob Ullah Khalid http://yasoob.me/
Book: Intermediate Python http://book.pythontips.com/
Blog: Python Tips http://pythontips.com/

On Sat, Dec 26, 2015 at 3:52 PM, Ratnadeep Debnath <notifications@github.com

**Comment by yasoob** [comment]
@rtnpro I am getting this error now when I try to connect it using Smuxi:

```
ERROR irc3.yasoob [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/irc3-0.8.3-py3.4.egg/irc3/__init__.py", line 142, in connection_made
    transport, protocol = f.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/lib/python3.4/asyncio/base_events.py", line 630, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.4/asyncio/base_events.py", line 612, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    return self.result()  # May raise too.
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 413, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable
```

Note: My internet is fully working.

**Comment by rtnpro** [comment]
Does Freenode listen on 6657? AFAIK, it usually listens on 6667 (Non SSL), 6697 (SSL), etc ports.

**Comment by yasoob** [comment]
Changing it to 6667 didn't fix the problem either.
